### ISSUE TITLE
Error on starting rfshell - ImportError: No module named readline

### ISSUE THREAD

**Issue by Tset-Noitamotua** [xyb/robotframework-debuglibrary#12]
Installed with `pip install robotframework-debuglibrary`

When calling `rfshell` in cmd on Windows 8.1 I´m getting following error:

```shell
C:\Users\Tset>rfshell
Traceback (most recent call last):
  File "C:\Python27\Scripts\rfshell-script.py", line 9, in <module>
    load_entry_point('robotframework-debuglibrary==0.4', 'console_scripts', 'rfshell')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2345, in load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python27\lib\site-packages\DebugLibrary.py", line 43, in <module>
    import readline
ImportError: No module named readline
```

**Comment by Tattoo** [comment]
You can install clone of readline with:

`pip install pyreadline`

to get the shell working on Windows

Maybe this could be a dependency for debuglibrary?

**Comment by xyb** [comment]
Sorry for the delayed reply. I believe this have been fixed in 2d76e5e, so I will close the issue, but feel free to reopen if you still have problem.

**Comment by Tattoo** [comment]
What do you think of adding pyreadline as a dependency for debuglibrary? that would work on all platforms then.

**Comment by Tset-Noitamotua** [comment]
I dont know much about readline and pyreadline either but I remember that installing readline on Windows did not work

```
[PYTHON_27] λ pip install readline
Collecting readline
  Downloading readline-6.2.4.1.tar.gz (2.3MB)
    100% |################################| 2.3MB 404kB/s
    Complete output from command python setup.py egg_info:
    error: this module is not meant to work on Windows

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\username\appdata\local\temp\pip-build-16firx\readline\
```

If you are sure that 'pyreadline' will work cross-platform then I think it's a better choice than 'readline'.

**Comment by xyb** [comment]
@Tattoo, @Tset-Noitamotua  I'm not familiar with pyreadline, but it looks like a good option for windows user. I do not have a windows environment, I would love if anyone can contribute and test about the pyreadline support.
