### ISSUE TITLE
Get value to a variable

### ISSUE THREAD

**Issue by serhatbolsu** [xyb/robotframework-debuglibrary#17]
Hello, 

So far debuglibrary helping me alot, only missing function is like setting the left hand side of a function.
```
# ex.  
${arg1}  set test variable  my_var_text
```

Is it possible to add this feature ?

**Comment by xyb** [comment]
Hi, @serhatbolsu, I remember its hard to implementation when I develop the debug library. But I'm not using robotframework for a long time, maybe it's easy now. Since I am not have enough time to dig into it, I will keep this issue open until someone implemented.

**Comment by xyb** [comment]
@serhatbolsu variable assignment supported now, please update to version 0.8.

**Comment by serhatbolsu** [comment]
Thank you @xyb and @jokimaki . However I wonder how it is not working for me since I use the `debug` keyword from inside an execution. I have tried `rfshell` it works there.

**Comment by xyb** [comment]
@serhatbolsu you may want to check if your virtualenv use the lastest version. Delete all previous versions in site-packages directory may be help also.
