### ISSUE TITLE
Not able to use `Set Variable` keyword from rfshell

### ISSUE THREAD

**Issue by Tset-Noitamotua** [xyb/robotframework-debuglibrary#18]
In a .robot file I can use `${label_id}=  Set Variable  SOME TEXT` to assign a value to `${label_id}`.

When I try the same in rfshell, I get this error:

```
> ${labe_id}=  Set Variable  SOME TEXT
< keyword: ${labe_id}=  Set Variable  SOME TEXT
! FAILED: ExecutionFailed(u"No keyword with name '${labe_id}=' found.",)
>
```

Am I doing something wrong or is it not implemented yet?

BTW: Thank you for this great library! It really speeds up test development a lot!

**Comment by xyb** [comment]
Hi, @Tset-Noitamotua, it's not implemented, same feature request had been recorded in #17. Love to welcome your contributions 😎

**Comment by xyb** [comment]
@Tset-Noitamotua variable assignment supported now, please update to version 0.8.

**Comment by Tset-Noitamotua** [comment]
YEAH! Thanks a lot for the update :-))))
Yet Upgraded and testing!

**Comment by Tset-Noitamotua** [comment]
How about special characters?

```
< keyword: ${label}=  Set Variable  SOME GERMÄN TÄXß
! FAILED: UnicodeDecodeError('utf8', '${label}=  Set Variable  SOME GERM\x8eN T\x8eX\xe1', 34, 35, 'invalid start byte')
>
```

Worth to open a new issue for that?

**Comment by Tset-Noitamotua** [comment]
I am on a Windows 7 64bit machine. Have no such env.
But locale is de_DE  ... I guess.
