### ISSUE TITLE
why Latest Version:  1.0.0  not support window Platforms

### ISSUE THREAD

**Issue by wangbixing** [xyb/robotframework-debuglibrary#24]
why Latest Version:  1.0.0  not support window Platforms

**Comment by xyb** [comment]
Thank you for reporting your issue, would you like to provide the detail of traceback or error messages?

**Comment by wangbixing** [comment]
Importing test library 'DebugLibrary' failed: ImportError: cannot import name STDLIBS

**Comment by xyb** [comment]
@wangbixing Robotframework 2.8 is too old to have STDLIBS, I will release a new version to change the minimum requirement of Robotframework to version 2.9.

**Comment by xyb** [comment]
@wangbixing new version released, please upgrade to 1.0.1

**Comment by wangbixing** [comment]
thks
