### ISSUE TITLE
Keyboard interrupt inside the interactive shell makes it unusable.

### ISSUE THREAD

**Issue by MrMino** [xyb/robotframework-debuglibrary#26]
Hi there! Thank you for this wonderful gem of a code.

Found an issue: sending a keyboard interrupt (by pushing ctrl+c) in the shell on one keyword, makes the shell unusable: 

    > Sleep    4 min             # Ctrl+C
    ^CSecond signal will force exit.
    ! keyword: Sleep    4 min
    ! Execution terminated by signal
    > Log    Hey
    ! keyword: Log    Hey
    ! Execution terminated by signal
    > Sleep    10 min
    ! keyword: Sleep    10 min
    ! Execution terminated by signal

**Comment by xyb** [comment]
I have found SIGINT's handler in robotframework's file `running/signalhandler.py`, which maintains a variable `_signal_count`. I believe reset it on-the-fly will avoid the `Execution forcefully stopped` exception and let the interactive shell keep work. But I do not have enough time to finish it recently. Contributions Welcome!

**Comment by MrMino** [comment]
If I'll find the time I'll surely send some code :).

**Comment by xyb** [comment]
@MrMino I have released a new version 1.1 to support this, you might want to try it.

**Comment by MrMino** [comment]
Will do! Thank you!
