### ISSUE TITLE
Interactive shell (feature request): print the value of a variable without 'Log' keyword.

### ISSUE THREAD

**Issue by MrMino** [xyb/robotframework-debuglibrary#27]
Currently, when you input a variable to the interactive shell without any other keyword, instead of showing it's value, the shell tries to execute it:

    > ${variable}   Set variable    some value
    # ${variable} = u'some value'
    > ${variable}
    ! keyword: ${variable}
    ! FAILED: TypeError('run_keyword() takes at least 2 arguments (1 given)',)

It would be great if the shell printed the value of it instead.

**Comment by xyb** [comment]
@MrMino good idea! Maybe I will implement it someday. But hey, contribution welcomes!

**Comment by xyb** [comment]
@MrMino I have released a new version 1.1 to support this, you might want to try it.
