### ISSUE TITLE
Import Library doesn't allow to pass arguments to the library

### ISSUE THREAD

**Issue by talgiat** [xyb/robotframework-debuglibrary#28]
When Trying to use in rfdebug shell:
Import Library  MyLibrary.py  arg1

We get an error saying Test Library 'MyLibrary' expected 1 argument, got 0.

The same code works fine if you just run it from robot.

**Comment by xyb** [comment]
@talgiat I have released a new version to fix this, please upgrade your local package and try it.

**Comment by talgiat** [comment]
@xyb Thanks so much for the quick fix. Seems to be good now. Any idea when you'll release 1.03 with the fix?

**Comment by xyb** [comment]
@talgiat the new version package had uploaded to pypi, you might want to upgrade your local package with `pip install --upgrade robotframework-debuglibrary`.
