### ISSUE TITLE
rfdebug raise PermissionError when running on Windows

### ISSUE THREAD

**Issue by KeithSmoland** [xyb/robotframework-debuglibrary#30]
This started happening after we update from v1.0.3 to v1.1.1, and updated python from 27 to 36.  When I run "rfshell" or "rfdebug" from the command line, I'm getting a permissions error(below).  My first guess is it has something to do with the refactoring commit that renames the files and changes from a suite to a file (commit 9edff34a91cde32da99266f639fd104c8bc6549f).  However, I don't get this error when using the "debug" keyword within a test to open the interactive shell.

> ksmoland@KSMOLAND-LT MINGW64 /c/git/automation-framework-cpp.reporting/BI/API/Tests/Objects from Content Store (dev)
> $ rfshell
> [ ERROR ] Parsing 'C:\Users\ksmoland\AppData\Local\Temp\robot-debug-kpm1lysz.txt' failed: PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ksmoland\\AppData\\Local\\Temp\\robot-debug-kpm1lysz.txt'
> 
> Try --help for usage information.
> 
> ksmoland@KSMOLAND-LT MINGW64 /c/git/automation-framework-cpp.reporting/BI/API/Tests/Objects from Content Store (dev)
> $ rfdebug
> [ ERROR ] Parsing 'C:\Users\ksmoland\AppData\Local\Temp\robot-debug-6xheiz2e.txt' failed: PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ksmoland\\AppData\\Local\\Temp\\robot-debug-6xheiz2e.txt'
> 
> Try --help for usage information.

**Comment by xyb** [comment]
@KeithSmoland Thank you for reporting this issue, I've released a new version 1.1.3 to fix it, please upgrade debuglibrary with `pip install --upgrade robotframework-debuglibrary`.
