### ISSUE TITLE
Does not support python3

### ISSUE THREAD

**Issue by bkhouri** [xyb/robotframework-debuglibrary#33]
With python2 approaching [EOL (end of life)](https://legacy.python.org/dev/peps/pep-0373/), this library needs to support python3 .

**Comment by xyb** [comment]
Hi, @bkhouri, sorry for the delay of reply, just came back from a trip. Yes, debuglibrary support python3 since 3 years ago(#8). If you have problem during install or using

**Comment by xyb** [comment]
Hi, @bkhouri, sorry for the delay of reply, just came back from a trip.

Yes, debuglibrary support python3 since 3 years ago(#8). Please let me know if you have problems when installing or using.
