### ISSUE TITLE
Keyword discovery fails with AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by Meallia** [xyb/robotframework-debuglibrary#34]
When executing the rfdebug script (or from a robot script) the k(eyword) action raises an attribute Error

The error is the same in py2 and py3.

`
rfdebug 
==============================================================================
robot-debug-FedQRa                                                            
==============================================================================
RFDEBUG REPL                                                          
>>>>> Enter interactive shell
Only accepted plain text format keyword seperated with two or more spaces.
Type "help" for more information.
> k
< Keywords of library BuiltIn
RFDEBUG REPL                                                          | FAIL |
AttributeError: 'str' object has no attribute 'name'
------------------------------------------------------------------------------
robot-debug-FedQRa                                                    | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  None
`

I'm in a clean venv with only those packages installed 
I also tried with robotframework 2.9.2

`
prompt-toolkit==1.0.15
Pygments==2.2.0
robotframework==3.0.4
robotframework-debuglibrary==1.1.3
six==1.11.0
wcwidth==0.1.7
`

I have a quick fix, i'll submit a pull request.

**Comment by xyb** [comment]
Thank your for your reporting and quick fix, version 1.1.4 fixed this.
