### ISSUE TITLE
upgrade to using prompt_toolkit v2

### ISSUE THREAD

**Issue by xyb** [xyb/robotframework-debuglibrary#36]
New prompt_toolkit v2 released which not backward compatible. Upgrade needed.

see also #31 and 3f3cdb6

**Comment by stdedos** [comment]
I know this won't make much difference, but `prompt-toolkit < 2` blocks from installing `ipython` fyi

**Comment by xyb** [comment]
@stdedos I have released a new version [2.0.0](https://pypi.org/project/robotframework-debuglibrary/2.0.0/) which using prompt-toolkit 2.x
