### ISSUE TITLE
Breaking back out of pdb

### ISSUE THREAD

**Issue by DanielPBak** [xyb/robotframework-debuglibrary#37]
Is it possible, after launching pdb through rfdebug, to return to rfdebug? If not, do you believe this would be a useful feature?

**Comment by xyb** [comment]
The pdb command in rfdebug is a private tool for developing debuglibrary, but yeah, maybe it's useful for other robotframework library developers. You should execute the pdb's `continue` command if you want back to rfdebug, not the `exit` command:

```
> pdb
break into python debugger: pdb
--Return--
> /Users/xyb/Projects/webtest/robotframework-debuglibrary/DebugLibrary.py(97)do_pdb()->None
-> pdb.set_trace()
(Pdb) help exit
q(uit) or exit - Quit from the debugger.
The program being executed is aborted.
(Pdb) help continue
c(ont(inue))
Continue execution, only stop when a breakpoint is encountered.
(Pdb) c
> Log to console  rfdebug now
rfdebug now
```
