### ISSUE TITLE
Step debugging .robot files in rfdebug

### ISSUE THREAD

**Issue by DanielPBak** [xyb/robotframework-debuglibrary#38]
Have you considered adding step-debugging capabilities to rfdebug? It seems as though it would be pretty useful. I may be able to implement this if you would accept the PR.

**Comment by xyb** [comment]
@DanielPBak sure, that's great! Feel free if you have any problem during development.

**Comment by xyb** [comment]
@DanielPBak version [2.1.0](https://pypi.org/project/robotframework-debuglibrary/2.1.0/) added step debugging capabilities.
