### ISSUE TITLE
NoConsoleScreenBufferError occurs on DebugLibrary execution

### ISSUE THREAD

**Issue by diannelli** [xyb/robotframework-debuglibrary#40]
Hi,

the following error occurs when I insert in my robot file the 'Debug' keyword;

'_**NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?**_'

![image](https://user-images.githubusercontent.com/16033815/45758469-f250e600-bc25-11e8-8729-56747ffb9522.png)

![image](https://user-images.githubusercontent.com/16033815/45759552-6f7d5a80-bc28-11e8-84ab-96b0ad2c039c.png)

I also imported DebugLibrary as suggested on usage instruction.

**Comment by xyb** [comment]
It's strange, I have no windows environment to repeat the issue, but this thread jonathanslenders/python-prompt-toolkit#406 maybe helpful for you.

**Comment by diannelli** [comment]
Also by using last version of python-prompt-toolkit issue persists.
I am using Python 3.5.2 on Pycharm (Windows 10)  and it seems that Pycharm is not able to run an external Windows console.

**Comment by DanielPBak** [comment]
Sounds like the solution is to just run your robot test in an external console. I'm not aware of any pycharm extension that would allow you to run a robot test internally. In any case this doesn't sound like a rfdebug issue

**Comment by xyb** [comment]
Considering the library has many changes since then, please upgrade to the new version and try your script again. If you still have this issue, please reopen.
