### ISSUE TITLE
AssertionError while using External Tools to run tests

### ISSUE THREAD

**Issue by piotr-mazur** [xyb/robotframework-debuglibrary#42]
to run a script I use https://www.screencast.com/t/WnJvaIG5c, 
PyCharm external tools - https://stackoverflow.com/questions/27256070/running-tests-on-pycharm-using-robot-framework
On Keyword 'Debug'  i have an AssertionError
https://www.screencast.com/t/q0zUCWFwMWr2

**Comment by xyb** [comment]
Apologies for the delayed response. Considering the library has many changes since then, please upgrade to the new version and try your script again. If you still have this issue, please reopen.
