### ISSUE TITLE
skip debug when not needed

### ISSUE THREAD

**Issue by fspegni** [xyb/robotframework-debuglibrary#45]
Hi, first of all thanks for this cool library.

I'm facing this scenario: I'm writing my tests and from time to time I need to insert the `Debug` keyword in order to stop the execution and inspect variables. However, when finished, I may forget to delete some `Debug` keyword from my tests, and this would block the testing task in my CI/CD pipeline.

Would it be useful to add some notion of "debug mode" such that when I write tests I set the  "debug mode" to ON, thus every `Debug` keyword actually stops the test execution, while on the CI/CD pipeline i can set the "debug mode" to OFF and every `Debug` keyword is returned immediately.

If this is not possible, I guess I can fork the project and send you a PR in the next weeks.

**Comment by tw39124-1** [comment]
As a suggestion, you could just wrap the Debug keyword in a Run Keyword If statement which checks for an environment variable. For example:

`Run Keyword If | %{DEBUG_DISABLED}=="1" | Debug`

Then in your CI/CD pipeline, ensure DEBUG_DISABLED is set to 1 to prevent the Debug keywords from stopping test execution.

**Comment by fspegni** [comment]
Hi, this is of course possible, but it requires all the test developers to adhere to this schema, and I would like to provide something easier to use (e.g. a `Debug If` keyword).

I try to work on a fork and send a PR when done

**Comment by xyb** [comment]
@fspegni @tw39124-1 I just released a new version [v2.2.0](https://pypi.org/project/robotframework-debuglibrary/2.2.0/) that adds the `Debug If` keyword.
