### ISSUE TITLE
Variables passed to Keywords are not accessible

### ISSUE THREAD

**Issue by bbbco** [xyb/robotframework-debuglibrary#5]
When you set the Debug statement inside of a Keyword, you cannot access the variable passed into the keyword inside the REPL debugger.

``` python
*** Keywords ***
Test REPL With Variables
    [Arguments]        ${var}
    Debug

=================

>>>>> Enter interactive shell, only accepted plain text format keyword.
> Log     ${var}
< keyword:  Log     ${var}
!  Non-existing variable '${var}'.
```

**Comment by xyb** [comment]
@bbbco variable assignment supported now, please upgrade to version 0.8.

**Comment by manycoding** [comment]
I cannot use any variables set at the start of a keyword from my Fedora 25 terminal, both from bash or sh. It always returns ! FAILED: ExecutionFailed(u"No keyword with name '${var}=' found.",).
However everything works fine in Windows 7 cmd and Alpine bash.
Any suggestions?
