### ISSUE TITLE
Syntax error because missing intendation on DebugLibrary line 232

### ISSUE THREAD

**Issue by kivipe** [xyb/robotframework-debuglibrary#50]
I am getting Intendation error because line 232 is missing intendation. This happens with 1.3.0.

**Comment by JoneSabino** [comment]
OMG something has happened while formatting! I gonna send a PR with full fix.

**Comment by VilleSalonen** [comment]
@JoneSabino Any updates on when this will be released to pip?

**Comment by JoneSabino** [comment]
I don't have permissions to merge... Waiting for @xyb

**Comment by xyb** [comment]
Sorry, guys, the bug-fix version [1.3.1](https://pypi.org/project/robotframework-debuglibrary/1.3.1/) is released.

And I have added functional testing for this project finally, I hope I do not let you all fail again.
