### ISSUE TITLE
[Feature Request]Step Debugging list or long list should show current debugging Section

### ISSUE THREAD

**Issue by Deep-Adhikary** [xyb/robotframework-debuglibrary#60]
While using step debugging, list or longlist always point on the main test where it was initialized. Not navigating to child keyword call. It would be helpful if it navigates.

current section(**debug console should show it in list**)
![image](https://user-images.githubusercontent.com/13049680/91637048-0a8d2a80-ea23-11ea-8349-f162c77ecf6f.png)
Debug Console
![image](https://user-images.githubusercontent.com/13049680/91637044-fea16880-ea22-11ea-941f-87e15dc8fbbb.png)
'l' output:
![image](https://user-images.githubusercontent.com/13049680/91637064-1d9ffa80-ea23-11ea-90e3-0ba0718f4b03.png)
'll' output
![image](https://user-images.githubusercontent.com/13049680/91637072-2c86ad00-ea23-11ea-8a39-c142fb9a9cae.png)

**Comment by xyb** [comment]
@Deep-Adhikary After examining the most recent debug library, it appears that the issue has been resolved. I'm going to close this now, but don't hesitate to reopen it if the problem persists.
