### ISSUE TITLE
Please add support of Robor3.2 with a new parser

### ISSUE THREAD

**Issue by tsrinivas7** [xyb/robotframework-debuglibrary#62]
I learned that the new parser of Robot framework 3.2 now comes with line number, which was addressed as part of https://github.com/robotframework/robotframework/issues/549 Can you please add support based on this? So that we can have full-fledged debugger like pdb?
I also found another older parser written by Bryan Oakley but the code doesn't exists anymore!

**Comment by xyb** [comment]
The new features are great, but I don't have enough time for it at the moment. It would be really nice if someone would like to contribute code.

**Comment by xylix** [comment]
@tsrinivas7 Robotframework-LSP provides a debugger nowadays. See https://github.com/robocorp/robotframework-lsp/tree/master/robotframework-ls/src/robotframework_debug_adapter for the code. I haven't used it personally but it could server your use case.

**Comment by xyb** [comment]
Implemented in [steplistener.py](https://github.com/xyb/robotframework-debuglibrary/blob/master/DebugLibrary/steplistener.py)
