### ISSUE TITLE
Does it work with RIDE?

### ISSUE THREAD

**Issue by Harm10** [xyb/robotframework-debuglibrary#70]
I am trying to work with this package within RIDE. Should it work in that environment?

**Comment by xyb** [comment]
@Harm10 Sorry for the delayed reply. Unfortunately, DebugLibrary does not work in RIDE right now. DebugLibrary is designed to run in a terminal and read user input from `sys.stdin`, but RIDE is a GUI application and its `sys.stdin` does not work properly. If you use DebugLibrary in RIDE, you will get an error message:
```
Warning: Input is not a terminal (fd=0).
```

In the future it may support using in GUI applications, but that would require a redesign of REPL, so there are no concrete plans for that right now.
