### ISSUE TITLE
Offering maintenance 

### ISSUE THREAD

**Issue by Snooz82** [xyb/robotframework-debuglibrary#78]
Dear Xie,
Dear William,

are you interested to hand over maintenance of DebugLibrary? 
i would be interested.
i sent you both an email with more details.

would he happy to hear from you.

Regards
René

**Comment by xyb** [comment]
@Snooz82 Sorry, just found your email about the project maintenance, I have replied and please take a look.

**Comment by Snooz82** [comment]
Thank you!
