### ISSUE TITLE
Assign variable in interactive shell

### ISSUE THREAD

**Issue by GitBartek** [xyb/robotframework-debuglibrary#9]
When i try to assign value in interactive shell i have message like below:
> ${var}     set variable     test_value
< keyword:  ${var}     set variable     test_value
!  No keyword with name '${var}' found.
>

**Comment by jollychang** [comment]
have a look #5 ?

**Comment by xyb** [comment]
@GitBartek variable assignment supported now, please upgrade to version 0.8.
